# Generated by Django 3.2.9 on 2021-12-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_icon',
            field=models.ImageField(default=True, upload_to='imgs'),
        ),
        migrations.AlterField(
            model_name='projectpicture',
            name='img_url',
            field=models.ImageField(upload_to='imgs', verbose_name='Image'),
        ),
    ]
