# Generated by Django 3.2.9 on 2021-12-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20211205_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_icon',
            field=models.ImageField(upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='projectpicture',
            name='img_url',
            field=models.ImageField(upload_to='profile_pic'),
        ),
    ]
