# Generated by Django 3.2.9 on 2021-12-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20211205_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_icon',
            field=models.ImageField(default='profile_pic/1.png', upload_to='profile_pic'),
        ),
        migrations.AlterField(
            model_name='projectpicture',
            name='img_url',
            field=models.ImageField(default='profile_pic/1.png', upload_to='profile_pic', verbose_name='Image'),
        ),
    ]
