# Generated by Django 3.2.9 on 2021-12-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20211205_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default='profile_pic/1.png', upload_to='profile_pic'),
        ),
    ]
